module.exports = {
  content: [
    "./src/**/*.{html,js,ts,jsx,tsx}",
    "app/**/*.{ts,tsx}",
    "components/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        brandwhite: "var(--brandwhite)",
        "foundation-blueblue-300": "var(--foundation-blueblue-300)",
        "foundation-blueblue-50": "var(--foundation-blueblue-50)",
        "foundation-blueblue-500": "var(--foundation-blueblue-500)",
        "foundation-blueblue-600": "var(--foundation-blueblue-600)",
        "foundation-blueblue-800": "var(--foundation-blueblue-800)",
        "foundation-blueblue-900": "var(--foundation-blueblue-900)",
        "foundation-greengreen-50": "var(--foundation-greengreen-50)",
        "foundation-greengreen-500": "var(--foundation-greengreen-500)",
        "foundation-greengreen-800": "var(--foundation-greengreen-800)",
        "foundation-greygrey-100": "var(--foundation-greygrey-100)",
        "foundation-greygrey-400": "var(--foundation-greygrey-400)",
        "foundation-greygrey-50": "var(--foundation-greygrey-50)",
        "foundation-greygrey-500": "var(--foundation-greygrey-500)",
        "foundation-greygrey-600": "var(--foundation-greygrey-600)",
        "foundation-greygrey-800": "var(--foundation-greygrey-800)",
        "foundation-orangeorange-50": "var(--foundation-orangeorange-50)",
        "foundation-orangeorange-500": "var(--foundation-orangeorange-500)",
        "foundation-orangeorange-600": "var(--foundation-orangeorange-600)",
        "foundation-orangeorange-700": "var(--foundation-orangeorange-700)",
        "foundation-purplepurple-50": "var(--foundation-purplepurple-50)",
        "foundation-purplepurple-500": "var(--foundation-purplepurple-500)",
        "foundation-purplepurple-800": "var(--foundation-purplepurple-800)",
        "foundation-whitewhite-100": "var(--foundation-whitewhite-100)",
        "foundation-whitewhite-200": "var(--foundation-whitewhite-200)",
        "foundation-whitewhite-300": "var(--foundation-whitewhite-300)",
        "foundation-whitewhite-50": "var(--foundation-whitewhite-50)",
        "grey-800": "var(--grey-800)",
        "grey-900": "var(--grey-900)",
        "greygrey-200": "var(--greygrey-200)",
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      fontFamily: {
        sans: [
          "ui-sans-serif",
          "system-ui",
          "sans-serif",
          '"Apple Color Emoji"',
          '"Segoe UI Emoji"',
          '"Segoe UI Symbol"',
          '"Noto Color Emoji"',
        ],
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
    container: { center: true, padding: "2rem", screens: { "2xl": "1400px" } },
  },
  plugins: [],
  darkMode: ["class"],
};
